title: Your awesome title
email: 197858770@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  -____-
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://red2090.github.io/blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: red40602025
github_username:  red2090

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
